Repository openebs/scope, pull requests merged in 2018-03, with the labels that each got.

#18 Add functionality to list PersistentVolumes and PersistentVolumeClaims
  probe/kubernetes/client.go
  probe/kubernetes/pv.go
  probe/kubernetes/reporter.go
  render/detailed/node.go
  render/detailed/summary.go
  render/pvc.go
  render/selectors.go
  report/id.go
  report/map_keys.go
  report/report.go
Labels: enhancement

#29 Add functionality to list all the storage classes under persistent volumes section
  probe/kubernetes/client.go
  probe/kubernetes/reporter.go
  probe/kubernetes/reporter_test.go
  probe/kubernetes/storageclass.go
  render/detailed/node.go
  render/detailed/summary.go
  render/pvc.go
  render/selectors.go
  report/id.go
  report/map_keys.go
  report/report.go
Labels: enhancement

#41 Add application pod and pvc details using Mock-json
  mock-server/README.md
  mock-server/json/app.json
  mock-server/json/pv.json
  mock-server/json/pvcdetail.json
  mock-server/mock-server.go
Labels: enhancement, good first issue

#39 Resolve conflict with ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: fix

#42 Fix indentation in filters.go
  probe/kubernetes/client.go
  probe/kubernetes/meta.go
  probe/kubernetes/reporter.go
  probe/kubernetes/reporter_test.go
  render/filters.go
Labels: fix

#53 List application pods under Persistent Volumes tab
  probe/kubernetes/applicationpod.go
  probe/kubernetes/client.go
  probe/kubernetes/meta.go
  probe/kubernetes/reporter.go
  probe/kubernetes/reporter_test.go
  render/detailed/node.go
  render/detailed/summary.go
  render/pvc.go
  render/selectors.go
  report/id.go
  report/map_keys.go
  report/report.go
Labels: enhancement

#58 Get all PV and PVC details when clicked on it
  probe/kubernetes/pv.go
  probe/kubernetes/pvc.go
  probe/kubernetes/reporter.go
  report/map_keys.go
Labels: enhancement

#63 Add all PV, PVC, and SC shape supports in backend
  report/report.go
Labels: fix

#64 Add details of Storage Class when clicked on any SC
  probe/kubernetes/reporter.go
  probe/kubernetes/storageclass.go
  report/map_keys.go
Labels: enhancement
